### ISSUE TITLE
can bus error

### ISSUE THREAD

**Issue by cloundliu** [hartkopp/nvidia-t18x-can#1]
I have connected the CAN_H/CANL to a vehicle CAN BUS, and then I use the follow command to enable the can controller:
ip link set can0 type can bitrate 500000 dbitrate 2000000 berr-reporting on fd on
ip link set up can0

Sometimes the can bus probably off because of these errors and sometimes it will run well in next inside period of time, no error occured.

**Comment by hartkopp** [comment]
Sorry. Please ask questions on the Linux CAN mailing list or in the NVIDIA forum.
This repository is for documentation only.
Thanks
